### ISSUE TITLE
tailwind v3 support

### ISSUE THREAD

**Issue by peterpalkovic** [cwsdigital/tailwind-utopia#5]
Hi, any tip how to get this plugin work with tailwind v3?
Thanks!

**Comment by pauldwight** [comment]
@chrispymm any thoughts?

**Comment by chrispymm** [comment]
I've just pushed an update - tagged v1.0.5 that should resolve any issues you may have been having.  

There was an issue with the default prefix having a `:` in.  It wasn't being parsed properly by tailwind.

I've updated the default prefix to be `fl-` instead of `fl:` and as far as I can see this is now working out of the box with tailwind v3.

**Comment by pauldwight** [comment]
Thanks @chrispymm
